---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Service
metadata:
  name: ctfwriteups-web-prod
  namespace: prod
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "ctfwriteups-web-prod"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "d0589aed-9c73-49c9-992e-10fcf79139e4"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "ctfwriteups.org"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
spec:
  type: LoadBalancer
  selector:
    app: ctfwriteups-web-prod
  ports:
    - port: 443
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfwriteups-web-prod
  namespace: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ctfwriteups-web-prod
      env: prod
      mode: web
  template:
    metadata:
      labels:
        app: ctfwriteups-web-prod
        env: prod
        mode: web
    spec:
      containers:
        - name: ctfwriteups-web-prod
          image: registry.digitalocean.com/ctfwriteups/ctfwriteups
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: PORT
              value: "8080"
            - name: ENV
              value: "prod"
